// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package db

import (
	"context"
	"database/sql"
)

const addAppDomain = `-- name: AddAppDomain :exec
INSERT INTO app_domains (id, app_id, domain, is_primary, tls_state)
VALUES (?, ?, ?, ?, ?)
`

type AddAppDomainParams struct {
	ID        string `json:"id"`
	AppID     string `json:"app_id"`
	Domain    string `json:"domain"`
	IsPrimary int64  `json:"is_primary"`
	TlsState  string `json:"tls_state"`
}

func (q *Queries) AddAppDomain(ctx context.Context, arg AddAppDomainParams) error {
	_, err := q.db.ExecContext(ctx, addAppDomain,
		arg.ID,
		arg.AppID,
		arg.Domain,
		arg.IsPrimary,
		arg.TlsState,
	)
	return err
}

const addAppPort = `-- name: AddAppPort :exec
INSERT INTO app_ports (id, app_id, container_port, protocol)
VALUES (?, ?, ?, ?)
`

type AddAppPortParams struct {
	ID            string `json:"id"`
	AppID         string `json:"app_id"`
	ContainerPort int64  `json:"container_port"`
	Protocol      string `json:"protocol"`
}

func (q *Queries) AddAppPort(ctx context.Context, arg AddAppPortParams) error {
	_, err := q.db.ExecContext(ctx, addAppPort,
		arg.ID,
		arg.AppID,
		arg.ContainerPort,
		arg.Protocol,
	)
	return err
}

const addAppVolume = `-- name: AddAppVolume :exec
INSERT INTO app_volumes (id, app_id, container_path, host_path, named_volume)
VALUES (?, ?, ?, ?, ?)
`

type AddAppVolumeParams struct {
	ID            string `json:"id"`
	AppID         string `json:"app_id"`
	ContainerPath string `json:"container_path"`
	HostPath      string `json:"host_path"`
	NamedVolume   string `json:"named_volume"`
}

func (q *Queries) AddAppVolume(ctx context.Context, arg AddAppVolumeParams) error {
	_, err := q.db.ExecContext(ctx, addAppVolume,
		arg.ID,
		arg.AppID,
		arg.ContainerPath,
		arg.HostPath,
		arg.NamedVolume,
	)
	return err
}

const clearAppEnv = `-- name: ClearAppEnv :exec
DELETE FROM app_env WHERE app_id = ?
`

func (q *Queries) ClearAppEnv(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, clearAppEnv, appID)
	return err
}

const clearAppPorts = `-- name: ClearAppPorts :exec
DELETE FROM app_ports WHERE app_id = ?
`

func (q *Queries) ClearAppPorts(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, clearAppPorts, appID)
	return err
}

const clearAppVolumes = `-- name: ClearAppVolumes :exec
DELETE FROM app_volumes WHERE app_id = ?
`

func (q *Queries) ClearAppVolumes(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, clearAppVolumes, appID)
	return err
}

const createApp = `-- name: CreateApp :exec
INSERT INTO apps (
    id, name, image_repo, current_version, instances, deploy_strategy,
    healthcheck_path, healthcheck_cmd, internal_only, memory_mb, cpu_pct,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAppParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ImageRepo       string `json:"image_repo"`
	CurrentVersion  string `json:"current_version"`
	Instances       int64  `json:"instances"`
	DeployStrategy  string `json:"deploy_strategy"`
	HealthcheckPath string `json:"healthcheck_path"`
	HealthcheckCmd  string `json:"healthcheck_cmd"`
	InternalOnly    int64  `json:"internal_only"`
	MemoryMb        int64  `json:"memory_mb"`
	CpuPct          int64  `json:"cpu_pct"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.Name,
		arg.ImageRepo,
		arg.CurrentVersion,
		arg.Instances,
		arg.DeployStrategy,
		arg.HealthcheckPath,
		arg.HealthcheckCmd,
		arg.InternalOnly,
		arg.MemoryMb,
		arg.CpuPct,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAppVersion = `-- name: CreateAppVersion :exec
INSERT INTO app_versions (id, app_id, version, image_tag, status, log_excerpt, deployed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAppVersionParams struct {
	ID         string `json:"id"`
	AppID      string `json:"app_id"`
	Version    string `json:"version"`
	ImageTag   string `json:"image_tag"`
	Status     string `json:"status"`
	LogExcerpt string `json:"log_excerpt"`
	DeployedAt int64  `json:"deployed_at"`
}

func (q *Queries) CreateAppVersion(ctx context.Context, arg CreateAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, createAppVersion,
		arg.ID,
		arg.AppID,
		arg.Version,
		arg.ImageTag,
		arg.Status,
		arg.LogExcerpt,
		arg.DeployedAt,
	)
	return err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApp, id)
	return err
}

const deleteAppDomain = `-- name: DeleteAppDomain :exec
DELETE FROM app_domains WHERE app_id = ? AND domain = ?
`

type DeleteAppDomainParams struct {
	AppID  string `json:"app_id"`
	Domain string `json:"domain"`
}

func (q *Queries) DeleteAppDomain(ctx context.Context, arg DeleteAppDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppDomain, arg.AppID, arg.Domain)
	return err
}

const deleteAppEnv = `-- name: DeleteAppEnv :exec
DELETE FROM app_env WHERE app_id = ? AND key = ?
`

type DeleteAppEnvParams struct {
	AppID string `json:"app_id"`
	Key   string `json:"key"`
}

func (q *Queries) DeleteAppEnv(ctx context.Context, arg DeleteAppEnvParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppEnv, arg.AppID, arg.Key)
	return err
}

const deleteAppVersionByID = `-- name: DeleteAppVersionByID :exec
DELETE FROM app_versions WHERE id = ?
`

func (q *Queries) DeleteAppVersionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAppVersionByID, id)
	return err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, image_repo, current_version, instances, deploy_strategy, healthcheck_path, healthcheck_cmd, internal_only, memory_mb, cpu_pct, created_at, updated_at, git_url, git_branch, git_dockerfile, git_token_encrypted, webhook_secret_encrypted FROM apps WHERE id = ?
`

func (q *Queries) GetAppByID(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageRepo,
		&i.CurrentVersion,
		&i.Instances,
		&i.DeployStrategy,
		&i.HealthcheckPath,
		&i.HealthcheckCmd,
		&i.InternalOnly,
		&i.MemoryMb,
		&i.CpuPct,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitUrl,
		&i.GitBranch,
		&i.GitDockerfile,
		&i.GitTokenEncrypted,
		&i.WebhookSecretEncrypted,
	)
	return i, err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, name, image_repo, current_version, instances, deploy_strategy, healthcheck_path, healthcheck_cmd, internal_only, memory_mb, cpu_pct, created_at, updated_at, git_url, git_branch, git_dockerfile, git_token_encrypted, webhook_secret_encrypted FROM apps WHERE name = ?
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageRepo,
		&i.CurrentVersion,
		&i.Instances,
		&i.DeployStrategy,
		&i.HealthcheckPath,
		&i.HealthcheckCmd,
		&i.InternalOnly,
		&i.MemoryMb,
		&i.CpuPct,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitUrl,
		&i.GitBranch,
		&i.GitDockerfile,
		&i.GitTokenEncrypted,
		&i.WebhookSecretEncrypted,
	)
	return i, err
}

const getAppGit = `-- name: GetAppGit :one
SELECT git_url, git_branch, git_dockerfile, git_token_encrypted, webhook_secret_encrypted
FROM apps WHERE id = ?
`

type GetAppGitRow struct {
	GitUrl                 string `json:"git_url"`
	GitBranch              string `json:"git_branch"`
	GitDockerfile          string `json:"git_dockerfile"`
	GitTokenEncrypted      []byte `json:"git_token_encrypted"`
	WebhookSecretEncrypted []byte `json:"webhook_secret_encrypted"`
}

func (q *Queries) GetAppGit(ctx context.Context, id string) (GetAppGitRow, error) {
	row := q.db.QueryRowContext(ctx, getAppGit, id)
	var i GetAppGitRow
	err := row.Scan(
		&i.GitUrl,
		&i.GitBranch,
		&i.GitDockerfile,
		&i.GitTokenEncrypted,
		&i.WebhookSecretEncrypted,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, user_id, action, target, payload_json, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Action      string         `json:"action"`
	Target      string         `json:"target"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   int64          `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.Target,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const listAllDomains = `-- name: ListAllDomains :many
SELECT id, app_id, domain, is_primary, tls_state FROM app_domains ORDER BY domain
`

func (q *Queries) ListAllDomains(ctx context.Context) ([]AppDomain, error) {
	rows, err := q.db.QueryContext(ctx, listAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppDomain{}
	for rows.Next() {
		var i AppDomain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Domain,
			&i.IsPrimary,
			&i.TlsState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppDomains = `-- name: ListAppDomains :many
SELECT id, app_id, domain, is_primary, tls_state FROM app_domains WHERE app_id = ? ORDER BY is_primary DESC, domain
`

func (q *Queries) ListAppDomains(ctx context.Context, appID string) ([]AppDomain, error) {
	rows, err := q.db.QueryContext(ctx, listAppDomains, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppDomain{}
	for rows.Next() {
		var i AppDomain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Domain,
			&i.IsPrimary,
			&i.TlsState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppEnv = `-- name: ListAppEnv :many
SELECT id, key, value_encrypted FROM app_env WHERE app_id = ? ORDER BY key
`

type ListAppEnvRow struct {
	ID             string `json:"id"`
	Key            string `json:"key"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) ListAppEnv(ctx context.Context, appID string) ([]ListAppEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppEnv, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppEnvRow{}
	for rows.Next() {
		var i ListAppEnvRow
		if err := rows.Scan(&i.ID, &i.Key, &i.ValueEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppPorts = `-- name: ListAppPorts :many
SELECT id, app_id, container_port, protocol FROM app_ports WHERE app_id = ?
`

func (q *Queries) ListAppPorts(ctx context.Context, appID string) ([]AppPort, error) {
	rows, err := q.db.QueryContext(ctx, listAppPorts, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPort{}
	for rows.Next() {
		var i AppPort
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ContainerPort,
			&i.Protocol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppVersionIDsToPrune = `-- name: ListAppVersionIDsToPrune :many
SELECT id FROM app_versions
WHERE app_id = ?
ORDER BY deployed_at DESC
LIMIT -1 OFFSET ?
`

type ListAppVersionIDsToPruneParams struct {
	AppID  string `json:"app_id"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAppVersionIDsToPrune(ctx context.Context, arg ListAppVersionIDsToPruneParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAppVersionIDsToPrune, arg.AppID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppVersions = `-- name: ListAppVersions :many
SELECT id, app_id, version, image_tag, status, log_excerpt, deployed_at FROM app_versions WHERE app_id = ? ORDER BY deployed_at DESC
`

func (q *Queries) ListAppVersions(ctx context.Context, appID string) ([]AppVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAppVersions, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppVersion{}
	for rows.Next() {
		var i AppVersion
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Version,
			&i.ImageTag,
			&i.Status,
			&i.LogExcerpt,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppVolumes = `-- name: ListAppVolumes :many
SELECT id, app_id, container_path, host_path, named_volume FROM app_volumes WHERE app_id = ?
`

func (q *Queries) ListAppVolumes(ctx context.Context, appID string) ([]AppVolume, error) {
	rows, err := q.db.QueryContext(ctx, listAppVolumes, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppVolume{}
	for rows.Next() {
		var i AppVolume
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ContainerPath,
			&i.HostPath,
			&i.NamedVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, name, image_repo, current_version, instances, deploy_strategy, healthcheck_path, healthcheck_cmd, internal_only, memory_mb, cpu_pct, created_at, updated_at, git_url, git_branch, git_dockerfile, git_token_encrypted, webhook_secret_encrypted FROM apps ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageRepo,
			&i.CurrentVersion,
			&i.Instances,
			&i.DeployStrategy,
			&i.HealthcheckPath,
			&i.HealthcheckCmd,
			&i.InternalOnly,
			&i.MemoryMb,
			&i.CpuPct,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GitUrl,
			&i.GitBranch,
			&i.GitDockerfile,
			&i.GitTokenEncrypted,
			&i.WebhookSecretEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesInstalled = `-- name: ListTemplatesInstalled :many
SELECT id, template_id, app_name, params_json, installed_at FROM templates_installed ORDER BY installed_at DESC
`

func (q *Queries) ListTemplatesInstalled(ctx context.Context) ([]TemplatesInstalled, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesInstalled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplatesInstalled{}
	for rows.Next() {
		var i TemplatesInstalled
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.AppName,
			&i.ParamsJson,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTemplateInstall = `-- name: RecordTemplateInstall :exec
INSERT INTO templates_installed (id, template_id, app_name, params_json, installed_at)
VALUES (?, ?, ?, ?, ?)
`

type RecordTemplateInstallParams struct {
	ID          string `json:"id"`
	TemplateID  string `json:"template_id"`
	AppName     string `json:"app_name"`
	ParamsJson  string `json:"params_json"`
	InstalledAt int64  `json:"installed_at"`
}

func (q *Queries) RecordTemplateInstall(ctx context.Context, arg RecordTemplateInstallParams) error {
	_, err := q.db.ExecContext(ctx, recordTemplateInstall,
		arg.ID,
		arg.TemplateID,
		arg.AppName,
		arg.ParamsJson,
		arg.InstalledAt,
	)
	return err
}

const setAppCurrentVersion = `-- name: SetAppCurrentVersion :exec
UPDATE apps SET current_version = ?, image_repo = ?, updated_at = ? WHERE id = ?
`

type SetAppCurrentVersionParams struct {
	CurrentVersion string `json:"current_version"`
	ImageRepo      string `json:"image_repo"`
	UpdatedAt      int64  `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) SetAppCurrentVersion(ctx context.Context, arg SetAppCurrentVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAppCurrentVersion,
		arg.CurrentVersion,
		arg.ImageRepo,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setAppGit = `-- name: SetAppGit :exec
UPDATE apps SET
    git_url = ?,
    git_branch = ?,
    git_dockerfile = ?,
    git_token_encrypted = ?,
    updated_at = ?
WHERE id = ?
`

type SetAppGitParams struct {
	GitUrl            string `json:"git_url"`
	GitBranch         string `json:"git_branch"`
	GitDockerfile     string `json:"git_dockerfile"`
	GitTokenEncrypted []byte `json:"git_token_encrypted"`
	UpdatedAt         int64  `json:"updated_at"`
	ID                string `json:"id"`
}

func (q *Queries) SetAppGit(ctx context.Context, arg SetAppGitParams) error {
	_, err := q.db.ExecContext(ctx, setAppGit,
		arg.GitUrl,
		arg.GitBranch,
		arg.GitDockerfile,
		arg.GitTokenEncrypted,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setAppWebhookSecret = `-- name: SetAppWebhookSecret :exec
UPDATE apps SET webhook_secret_encrypted = ?, updated_at = ? WHERE id = ?
`

type SetAppWebhookSecretParams struct {
	WebhookSecretEncrypted []byte `json:"webhook_secret_encrypted"`
	UpdatedAt              int64  `json:"updated_at"`
	ID                     string `json:"id"`
}

func (q *Queries) SetAppWebhookSecret(ctx context.Context, arg SetAppWebhookSecretParams) error {
	_, err := q.db.ExecContext(ctx, setAppWebhookSecret, arg.WebhookSecretEncrypted, arg.UpdatedAt, arg.ID)
	return err
}

const updateApp = `-- name: UpdateApp :exec
UPDATE apps SET
    image_repo = ?,
    current_version = ?,
    instances = ?,
    deploy_strategy = ?,
    healthcheck_path = ?,
    healthcheck_cmd = ?,
    internal_only = ?,
    memory_mb = ?,
    cpu_pct = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAppParams struct {
	ImageRepo       string `json:"image_repo"`
	CurrentVersion  string `json:"current_version"`
	Instances       int64  `json:"instances"`
	DeployStrategy  string `json:"deploy_strategy"`
	HealthcheckPath string `json:"healthcheck_path"`
	HealthcheckCmd  string `json:"healthcheck_cmd"`
	InternalOnly    int64  `json:"internal_only"`
	MemoryMb        int64  `json:"memory_mb"`
	CpuPct          int64  `json:"cpu_pct"`
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) error {
	_, err := q.db.ExecContext(ctx, updateApp,
		arg.ImageRepo,
		arg.CurrentVersion,
		arg.Instances,
		arg.DeployStrategy,
		arg.HealthcheckPath,
		arg.HealthcheckCmd,
		arg.InternalOnly,
		arg.MemoryMb,
		arg.CpuPct,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAppVersionStatus = `-- name: UpdateAppVersionStatus :exec
UPDATE app_versions SET status = ?, log_excerpt = ? WHERE id = ?
`

type UpdateAppVersionStatusParams struct {
	Status     string `json:"status"`
	LogExcerpt string `json:"log_excerpt"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateAppVersionStatus(ctx context.Context, arg UpdateAppVersionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAppVersionStatus, arg.Status, arg.LogExcerpt, arg.ID)
	return err
}

const upsertAppEnv = `-- name: UpsertAppEnv :exec
INSERT INTO app_env (id, app_id, key, value_encrypted) VALUES (?, ?, ?, ?)
ON CONFLICT(app_id, key) DO UPDATE SET value_encrypted = excluded.value_encrypted
`

type UpsertAppEnvParams struct {
	ID             string `json:"id"`
	AppID          string `json:"app_id"`
	Key            string `json:"key"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

func (q *Queries) UpsertAppEnv(ctx context.Context, arg UpsertAppEnvParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppEnv,
		arg.ID,
		arg.AppID,
		arg.Key,
		arg.ValueEncrypted,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
