// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, user_id, "action", target, payload_json, created_at FROM audit_log
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Target,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogForTarget = `-- name: ListAuditLogForTarget :many
SELECT id, user_id, "action", target, payload_json, created_at FROM audit_log
WHERE target = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAuditLogForTargetParams struct {
	Target string `json:"target"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAuditLogForTarget(ctx context.Context, arg ListAuditLogForTargetParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogForTarget, arg.Target, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Target,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
