// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (id, user_id, name, hash, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Hash      string `json:"hash"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Hash,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at FROM sessions WHERE id = ? AND expires_at > ?
`

type GetSessionParams struct {
	ID        string `json:"id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, name, hash, last_used_at, created_at, revoked_at FROM tokens WHERE hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Hash,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, name, last_used_at, created_at, revoked_at
FROM tokens WHERE user_id = ? ORDER BY created_at DESC
`

type ListTokensByUserRow struct {
	ID         string        `json:"id"`
	Name       string        `json:"name"`
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	CreatedAt  int64         `json:"created_at"`
	RevokedAt  sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListTokensByUser(ctx context.Context, userID string) ([]ListTokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensByUserRow{}
	for rows.Next() {
		var i ListTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredSessions, expiresAt)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens SET revoked_at = ? WHERE id = ? AND user_id = ?
`

type RevokeTokenParams struct {
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.ID, arg.UserID)
	return err
}

const touchToken = `-- name: TouchToken :exec
UPDATE tokens SET last_used_at = ? WHERE id = ?
`

type TouchTokenParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         string        `json:"id"`
}

func (q *Queries) TouchToken(ctx context.Context, arg TouchTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchToken, arg.LastUsedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
