// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type App struct {
	ID                     string `json:"id"`
	Name                   string `json:"name"`
	ImageRepo              string `json:"image_repo"`
	CurrentVersion         string `json:"current_version"`
	Instances              int64  `json:"instances"`
	DeployStrategy         string `json:"deploy_strategy"`
	HealthcheckPath        string `json:"healthcheck_path"`
	HealthcheckCmd         string `json:"healthcheck_cmd"`
	InternalOnly           int64  `json:"internal_only"`
	MemoryMb               int64  `json:"memory_mb"`
	CpuPct                 int64  `json:"cpu_pct"`
	CreatedAt              int64  `json:"created_at"`
	UpdatedAt              int64  `json:"updated_at"`
	GitUrl                 string `json:"git_url"`
	GitBranch              string `json:"git_branch"`
	GitDockerfile          string `json:"git_dockerfile"`
	GitTokenEncrypted      []byte `json:"git_token_encrypted"`
	WebhookSecretEncrypted []byte `json:"webhook_secret_encrypted"`
}

type AppDomain struct {
	ID        string `json:"id"`
	AppID     string `json:"app_id"`
	Domain    string `json:"domain"`
	IsPrimary int64  `json:"is_primary"`
	TlsState  string `json:"tls_state"`
}

type AppEnv struct {
	ID             string `json:"id"`
	AppID          string `json:"app_id"`
	Key            string `json:"key"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

type AppPort struct {
	ID            string `json:"id"`
	AppID         string `json:"app_id"`
	ContainerPort int64  `json:"container_port"`
	Protocol      string `json:"protocol"`
}

type AppVersion struct {
	ID         string `json:"id"`
	AppID      string `json:"app_id"`
	Version    string `json:"version"`
	ImageTag   string `json:"image_tag"`
	Status     string `json:"status"`
	LogExcerpt string `json:"log_excerpt"`
	DeployedAt int64  `json:"deployed_at"`
}

type AppVolume struct {
	ID            string `json:"id"`
	AppID         string `json:"app_id"`
	ContainerPath string `json:"container_path"`
	HostPath      string `json:"host_path"`
	NamedVolume   string `json:"named_volume"`
}

type AuditLog struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Action      string         `json:"action"`
	Target      string         `json:"target"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   int64          `json:"created_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TemplatesInstalled struct {
	ID          string `json:"id"`
	TemplateID  string `json:"template_id"`
	AppName     string `json:"app_name"`
	ParamsJson  string `json:"params_json"`
	InstalledAt int64  `json:"installed_at"`
}

type Token struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	Hash       string        `json:"hash"`
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	CreatedAt  int64         `json:"created_at"`
	RevokedAt  sql.NullInt64 `json:"revoked_at"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}
