// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddAppDomain(ctx context.Context, arg AddAppDomainParams) error
	AddAppPort(ctx context.Context, arg AddAppPortParams) error
	AddAppVolume(ctx context.Context, arg AddAppVolumeParams) error
	ClearAppEnv(ctx context.Context, appID string) error
	ClearAppPorts(ctx context.Context, appID string) error
	ClearAppVolumes(ctx context.Context, appID string) error
	CountUsers(ctx context.Context) (int64, error)
	CreateApp(ctx context.Context, arg CreateAppParams) error
	CreateAppVersion(ctx context.Context, arg CreateAppVersionParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteApp(ctx context.Context, id string) error
	DeleteAppDomain(ctx context.Context, arg DeleteAppDomainParams) error
	DeleteAppEnv(ctx context.Context, arg DeleteAppEnvParams) error
	DeleteAppVersionByID(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	GetAppByID(ctx context.Context, id string) (App, error)
	GetAppByName(ctx context.Context, name string) (App, error)
	GetAppGit(ctx context.Context, id string) (GetAppGitRow, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTokenByHash(ctx context.Context, hash string) (Token, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	ListAllDomains(ctx context.Context) ([]AppDomain, error)
	ListAppDomains(ctx context.Context, appID string) ([]AppDomain, error)
	ListAppEnv(ctx context.Context, appID string) ([]ListAppEnvRow, error)
	ListAppPorts(ctx context.Context, appID string) ([]AppPort, error)
	ListAppVersionIDsToPrune(ctx context.Context, arg ListAppVersionIDsToPruneParams) ([]string, error)
	ListAppVersions(ctx context.Context, appID string) ([]AppVersion, error)
	ListAppVolumes(ctx context.Context, appID string) ([]AppVolume, error)
	ListApps(ctx context.Context) ([]App, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListAuditLogForTarget(ctx context.Context, arg ListAuditLogForTargetParams) ([]AuditLog, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListTemplatesInstalled(ctx context.Context) ([]TemplatesInstalled, error)
	ListTokensByUser(ctx context.Context, userID string) ([]ListTokensByUserRow, error)
	PurgeExpiredSessions(ctx context.Context, expiresAt int64) error
	RecordTemplateInstall(ctx context.Context, arg RecordTemplateInstallParams) error
	RevokeToken(ctx context.Context, arg RevokeTokenParams) error
	SetAppCurrentVersion(ctx context.Context, arg SetAppCurrentVersionParams) error
	SetAppGit(ctx context.Context, arg SetAppGitParams) error
	SetAppWebhookSecret(ctx context.Context, arg SetAppWebhookSecretParams) error
	TouchToken(ctx context.Context, arg TouchTokenParams) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
	UpdateAppVersionStatus(ctx context.Context, arg UpdateAppVersionStatusParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertAppEnv(ctx context.Context, arg UpsertAppEnvParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
