/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_embla-carousel@8.6.0_typescript@5.6.3_vite@5.4.21_l_0792737e911435bc3e7231c7ff24c462/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
